import type { Metadata } from "next";
import { siteConfig } from "@/lib/config";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${siteConfig.name}.`,
  alternates: { canonical: `${siteConfig.url}/terms` },
};

export default function TermsPage() {
  return (
    <div className="pt-24 pb-20">
      <div className="container-page max-w-3xl">
        {/* Header */}
        <div className="mb-12">
          <div className="inline-block px-3 py-1 text-xs font-semibold uppercase tracking-widest text-[var(--accent)] bg-[var(--accent-muted)] rounded-full border border-[var(--accent)]/20 mb-4">
            Legal
          </div>
          <h1 className="text-display-md text-[var(--text-primary)] mb-3">
            Terms of Service
          </h1>
          <p className="text-sm text-[var(--text-tertiary)]">
            Last Updated: {siteConfig.lastUpdated}
          </p>
        </div>

        <div className="legal-content">

          <h2>1. Acceptance of Terms</h2>
          <p>
            By downloading, installing, or using the Moonlight AI application (&quot;the App&quot; or &quot;Service&quot;), 
            you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, 
            do not use the App.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Moonlight AI is a local-first AI assistant application for Android that enables you to run 
            compatible AI language models directly on your device. The App provides:
          </p>
          <ul>
            <li>On-device AI inference using locally installed GGUF models</li>
            <li>A Model Store for downloading compatible AI models from Hugging Face</li>
            <li>Local conversation storage and memory features</li>
            <li>Optional Android system voice input and text-file attachments</li>
            <li>Local memory and separate workspace features</li>
          </ul>

          <h2>3. User Responsibilities</h2>
          <p>You agree to use the App only for lawful purposes. You are responsible for:</p>
          <ul>
            <li>Ensuring your use of the App complies with applicable laws and regulations</li>
            <li>The content you generate, upload, or process using the App</li>
            <li>Verifying the suitability of any AI-generated content before relying on it</li>
            <li>Complying with the license terms of any AI models you download and use</li>
            <li>Maintaining appropriate backups of any data you store in the App</li>
          </ul>

          <h2>4. AI-Generated Content Disclaimer</h2>
          <p>
            AI-generated content produced by Moonlight AI is generated by large language models running 
            locally on your device. Such content:
          </p>
          <ul>
            <li>May be inaccurate, incomplete, or inappropriate</li>
            <li>Should not be relied upon as professional advice (medical, legal, financial, or otherwise)</li>
            <li>May reflect biases or limitations of the underlying AI model</li>
            <li>Is generated probabilistically and may vary between runs</li>
          </ul>
          <p>
            You use AI-generated content at your own risk. Moonlight AI makes no warranties 
            regarding the accuracy, reliability, or suitability of AI-generated outputs.
          </p>

          <h2>5. AI Model Licensing</h2>
          <p>
            AI models available in the Model Store are provided by third-party model creators 
            and distributed via Hugging Face. Each model is subject to its own license terms, 
            which may include restrictions on commercial use, distribution, or modification. 
            You are responsible for reviewing and complying with the license terms of any 
            model you download and use.
          </p>
          <p>
            Moonlight AI does not grant any license to the underlying model weights beyond 
            what is provided by the original model creators.
          </p>

          <h2>6. Third-Party Model Sources</h2>
          <p>
            Models are downloaded from Hugging Face (huggingface.co). Your access to model 
            downloads is subject to Hugging Face&apos;s Terms of Service. Moonlight AI is not 
            responsible for the availability, accuracy, or content of models hosted on 
            third-party platforms.
          </p>

          <h2>7. Intellectual Property</h2>
          <p>
            Moonlight AI and its original content, features, and functionality are owned by 
            {" "}{siteConfig.companyName}. The App is provided for personal use. 
            You may not copy, modify, distribute, or create derivative works of the App 
            without express written permission.
          </p>

          <h2>8. Prohibited Use</h2>
          <p>You agree not to use the App to:</p>
          <ul>
            <li>Generate content that is illegal, harmful, or violates the rights of others</li>
            <li>Generate, distribute, or store child sexual abuse material (CSAM)</li>
            <li>Violate applicable laws or regulations</li>
            <li>Attempt to reverse engineer, decompile, or extract the App&apos;s source code</li>
            <li>Use the App in ways that violate the license terms of installed AI models</li>
          </ul>

          <h2>9. Service Availability</h2>
          <p>
            Moonlight AI is provided as-is. Core AI inference functionality does not require 
            an internet connection after models are installed. However, model downloads, 
            software updates, and any future features requiring network access depend on 
            third-party services and network availability, which we cannot guarantee.
          </p>

          <h2>10. Updates and Changes</h2>
          <p>
            We may update the App and these Terms from time to time. Continued use of the App 
            after updates constitutes acceptance of the revised Terms. We will update the 
            &quot;Last Updated&quot; date when these Terms change.
          </p>

          <h2>11. Disclaimer of Warranties</h2>
          <p>
            THE APP IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, 
            EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, 
            FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT 
            THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
          </p>

          <h2>12. Limitation of Liability</h2>
          <p>
            TO THE FULLEST EXTENT PERMITTED BY LAW, {siteConfig.companyName.toUpperCase()} SHALL NOT BE 
            LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES 
            ARISING FROM YOUR USE OF THE APP OR ITS CONTENT, EVEN IF ADVISED OF THE 
            POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p>
            <em>Note: This limitation of liability section is a standard clause and should be 
            reviewed by qualified legal counsel before relying on it in your jurisdiction.</em>
          </p>

          <h2>13. Termination</h2>
          <p>
            You may stop using the App at any time. Because the App does not require an account, 
            there is no account to terminate. Uninstalling the App removes all locally stored data.
          </p>

          <h2>14. Contact</h2>
          <p>
            For questions about these Terms of Service, please contact:{" "}
            <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a>
          </p>

        </div>
      </div>
    </div>
  );
}
