import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/lib/config";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${siteConfig.name} v1.7.x. Guidelines for on-device inference, computer connections, and cloud provider usage.`,
  alternates: { canonical: `${siteConfig.url}/terms` },
};

export default function TermsPage() {
  return (
    <div className="pt-24 pb-20">
      <div className="container-page max-w-3xl">
        {/* Header */}
        <div className="mb-12">
          <div className="inline-block px-3 py-1 text-xs font-semibold uppercase tracking-widest text-[var(--accent)] bg-[var(--accent-muted)] rounded-full border border-[var(--accent)]/20 mb-4">
            Legal
          </div>
          <h1 className="text-display-md text-[var(--text-primary)] mb-3">
            Terms of Service
          </h1>
          <p className="text-sm text-[var(--text-tertiary)]">
            Last Updated: {siteConfig.lastUpdated} · {siteConfig.releaseScope}
          </p>
        </div>

        <div className="legal-content">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By downloading, installing, accessing, or using the Moonlight AI application (&quot;the App&quot;) or visiting this website (&quot;the Site&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not install, access, or use the App or Site.
          </p>
          <p>
            These Terms constitute an agreement between you and {siteConfig.companyName} (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          </p>

          <h2>2. Description of the Service and Execution Modes</h2>
          <p>
            Moonlight AI is a privacy-focused, local-first artificial intelligence assistant developed for Android devices. The App provides three execution modes:
          </p>
          <ul>
            <li>
              <strong>Phone Mode:</strong> Runs compatible GGUF open-weight language models directly on your Android device using on-device inference. Once the required model is downloaded to your device, Phone mode does not send prompts to cloud AI providers and can operate without an internet connection.
            </li>
            <li>
              <strong>Computer Mode:</strong> Connects Moonlight to your own user-configured LM Studio server running on your computer. Computation takes place on your designated computer or local network.
            </li>
            <li>
              <strong>Cloud Mode:</strong> Connects Moonlight to supported third-party cloud AI providers (including OpenAI, Anthropic, Google Gemini, Alibaba Cloud, NVIDIA, or compatible endpoints) using API keys that you supply.
            </li>
          </ul>

          <h2>3. AI Output Limitations and User Disclaimers</h2>
          <p>
            You acknowledge and understand that language models generate text probabilistically based on pattern matching and statistical associations. Consequently:
          </p>
          <ul>
            <li>
              <strong>Potential Inaccuracy:</strong> AI outputs may be inaccurate, incomplete, misleading, or out of date. You must independently verify any critical facts, figures, advice, or code.
            </li>
            <li>
              <strong>Not Professional Advice:</strong> Outputs generated by Moonlight AI do not constitute professional medical, legal, financial, architectural, or technical advice. Never make high-stakes decisions based solely on AI-generated text.
            </li>
            <li>
              <strong>Biases and Content Limitations:</strong> Models may reflect unintended biases or limitations present in their training datasets.
            </li>
            <li>
              <strong>Variability:</strong> Responses to identical prompts may vary across runs and between different models.
            </li>
          </ul>
          <p>
            You assume full responsibility for your use of and reliance upon any outputs produced through the App.
          </p>

          <h2>4. Third-Party Cloud Providers and External Services</h2>
          <p>
            When you use Cloud mode or connect external services:
          </p>
          <ul>
            <li>
              <strong>Provider Terms and Policies:</strong> You are subject to the terms of service, acceptable use policies, and privacy policies of each respective provider (e.g., OpenAI, Anthropic, Google, Alibaba, NVIDIA). You agree to comply with those terms.
            </li>
            <li>
              <strong>API Keys and Billing:</strong> You are solely responsible for obtaining, funding, and securing your own API keys. Any billing, charges, rate limits, or account suspensions imposed by third-party providers are strictly between you and that provider.
            </li>
            <li>
              <strong>Data Transmission:</strong> In Cloud mode, prompts, recent conversation context, and attached text are transmitted over the internet to the selected provider. Moonlight AI does not control how third-party providers log or retain data sent via their APIs.
            </li>
          </ul>

          <h2>5. Model Licensing and Distribution</h2>
          <p>
            Language models available for download in Phone mode are open-weight models distributed by third-party creators via Hugging Face. Each model is governed by its author&apos;s license (such as Apache 2.0, MIT, Llama Community License, or OpenRAIL).
          </p>
          <p>
            You agree to review and comply with the applicable license terms of each model you download. {siteConfig.companyName} does not own, author, or grant licenses to third-party model weights.
          </p>

          <h2>6. Acceptable Use and Prohibited Misuse</h2>
          <p>
            You agree to use Moonlight AI only for lawful and responsible purposes. You specifically agree not to use the App, in any execution mode, to:
          </p>
          <ul>
            <li>Generate, store, transmit, or promote child sexual abuse material (CSAM) or child sexual exploitation and abuse (CSAE).</li>
            <li>Generate content that promotes self-harm, suicide, violence, or illegal acts.</li>
            <li>Infringe upon the intellectual property, privacy, or legal rights of any third party.</li>
            <li>Generate malicious code, malware, or automate cyberattacks.</li>
            <li>Harass, threaten, defraud, or impersonate individuals or entities.</li>
            <li>Attempt to reverse engineer, decompile, or tamper with the security controls of the App, except to the extent permitted by applicable law.</li>
          </ul>

          <h2>7. In-App AI Response Reporting</h2>
          <p>
            Moonlight includes an in-app feature enabling you to report AI responses that appear incorrect, unsafe, or inappropriate. Submitting a report transmits the flagged response, prompt, model identifier, and issue category.
          </p>
          <p>
            While reporting helps us investigate safety and quality issues, {siteConfig.companyName} makes no representation that every reported output will be reviewed individually, nor do we guarantee that the App will filter or prevent every potentially harmful output.
          </p>

          <h2>8. Intellectual Property</h2>
          <p>
            The Moonlight AI application, branding, trademarks, logos, visual designs, and website content are the intellectual property of {siteConfig.companyName}. All rights not expressly granted to you under these Terms are reserved.
          </p>
          <p>
            To the maximum extent permitted by applicable law, we claim no ownership rights in the prompts you provide or the text outputs generated for you by local or cloud models.
          </p>

          <h2>9. Service Availability and Updates</h2>
          <p>
            Moonlight AI is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. While local Phone mode can operate offline after setup, online capabilities (such as model downloads, LM Studio remote connections, and Cloud provider requests) depend on network connectivity and third-party availability.
          </p>
          <p>
            We may update, modify, or discontinue features of the App from time to time without prior notice.
          </p>

          <h2>10. Disclaimer of Warranties</h2>
          <p>
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE APP AND SERVICE ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, AND NON-INFRINGEMENT.
          </p>
          <p>
            WE DO NOT WARRANT THAT THE APP WILL MEET YOUR REQUIREMENTS, BE UNINTERRUPTED, SECURE, ACCURATE, OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED.
          </p>

          <h2>11. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL {siteConfig.companyName.toUpperCase()}, ITS AFFILIATES, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS, DATA, GOODWILL, WORK STOPPAGE, HARDWARE MALFUNCTION, OR BUSINESS INTERRUPTION) ARISING OUT OF OR IN CONNECTION WITH YOUR USE OR INABILITY TO USE THE APP, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p>
            <em>
              Note: Some jurisdictions do not allow the exclusion of certain warranties or the limitation of liability for incidental or consequential damages. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law. This section should be reviewed by qualified legal counsel in relevant jurisdictions.
            </em>
          </p>

          <h2>12. Termination</h2>
          <p>
            You may terminate your agreement with these Terms at any time by stopping all use of the App and uninstalling it from your devices. Because Moonlight does not require an account, there is no central account to close.
          </p>

          <h2>13. Governing Law and Disputes</h2>
          <p>
            These Terms shall be interpreted and governed in accordance with applicable laws, without regard to conflict of law provisions. If any provision of these Terms is found to be invalid or unenforceable, that provision shall be enforced to the maximum extent permissible, and the remaining provisions shall remain in full force and effect.
          </p>

          <h2>14. Contact Information</h2>
          <p>
            If you have questions or concerns regarding these Terms of Service, please contact:
          </p>
          <p>
            <strong>{siteConfig.companyName}</strong><br />
            Support: <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a><br />
            Online: <Link href="/support">Help &amp; Support Centre</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
