export interface FaqItem { q:string; a:string; }
export interface FaqCategory { id:string; title:string; questions:FaqItem[]; }
export const faqCategories:FaqCategory[]=[
{id:"getting-started",title:"Getting Started",questions:[{q:"What is Moonlight AI?",a:"An Android assistant with Phone, Computer and Cloud model choices. The 1.6.1 preview adds the Glass interface, LM Studio setup and compact LFM downloads."},{q:"Do I need an account or subscription?",a:"No Moonlight account is required. Phone inference uses your device. Cloud providers require your own credentials and may charge for inference and web tools; private-network services may have separate terms."},{q:"Does it work offline?",a:"Phone chat can work offline after downloading a compatible model. Computer mode needs a reachable server; cloud services, model downloads and some Android speech services need network access."}]},
{id:"models",title:"Models & Connections",questions:[{q:"Which phone models are available?",a:"The new catalog offers official Liquid AI LFM2 350M, LFM2 700M and LFM2.5 1.2B Q4_K_M files from pinned Hugging Face revisions. Existing installed models are preserved. Physical-phone LFM inference remains unverified in the preview."},{q:"How much storage and memory do I need?",a:"Downloads are about 229 MB, 469 MB and 731 MB. Allow extra space for the app. Phone inference requires ARM64, at least 4 GiB total RAM and available RAM greater than model size plus 1.5 GiB; eligibility is checked again before loading."},{q:"Can I use LM Studio away from home?",a:"Yes, when your authenticated HTTPS server is reachable over a separately configured private network. Follow Settings → LM Studio → From anywhere. Your computer must remain awake. Moonlight does not directly pair with LM Link."}]},
{id:"performance",title:"Performance",questions:[{q:"How fast is local chat?",a:"Speed and battery use depend on the device, model and available memory. No physical-phone speed benchmark is claimed for this preview."},{q:"Why is a model unavailable?",a:"The capacity checks may reject it based on architecture, total RAM, available RAM or file size. Try an eligible smaller model, or use Computer or Cloud mode. Checks cannot guarantee device safety."}]},
{id:"privacy",title:"Privacy & Security",questions:[{q:"Does my data leave my phone?",a:"Phone inference stays local. Computer and Cloud requests can send up to 20 recent messages, personal instructions and attached text to the selected service after a send disclosure. Saved memories are not automatically included. Downloads and Android system services have their own network behavior."},{q:"Are API keys encrypted?",a:"The native credential store protects API keys and LM Studio tokens with AES-GCM and Android Keystore. This is separate from local conversation storage. Private-network HTTP is not encrypted in transit unless protected by another layer."},{q:"Does deleting a chat delete it everywhere?",a:"Deleting removes the local conversation. It does not remove server logs, provider records, emails or shared copies. Manage those with the service or server operator. You can also remove saved connections and revoke keys at the provider."},{q:"Do you add tracking?",a:"The current app has no analytics, advertising or remote crash-reporting SDK. Selected cloud services, Google Play, model-download hosts and Android system services have their own data practices."}]},
{id:"troubleshooting",title:"Troubleshooting",questions:[{q:"LM Studio does not show models",a:"Check the visible connection status above the form. Verify the server is running, the address is reachable and the token is correct. Use the API server address, not localhost or an LM Link invitation. An empty catalog now has an explicit status."},{q:"My provider request failed",a:"Check the key, account allowance, region permissions and model ID. Refresh the catalog or choose a supported text model. Image/video generation and vision are not included in this preview."},{q:"Model download failed",a:"Check your connection and free storage, then retry an eligible model in Models & storage. Do not bypass a failed capacity check."}]}
];
