import { Brain, Palette, Globe, ShieldCheck, Mic, MessageSquare, SlidersHorizontal, FileCheck, Cpu, Monitor, Cloud, Download } from "lucide-react";
export type FeatureStatus = "RELEASED" | "PREVIEW" | "BETA" | "ALPHA" | "MODEL-DEPENDENT" | "IN DEVELOPMENT";
export interface Feature { id:string; title:string; headline:string; description:string; technical:string; benefit:string; icon:import("lucide-react").LucideIcon; color:string; note?:string; status:FeatureStatus; }
// Source: Android 1.6.1 checkpoint, ChatScreen, providers, LMStudioScreen, model catalog.
export const features:Feature[] = [
{id:"local-inference",title:"Phone intelligence",headline:"Make room for your next idea.",description:"Run compatible compact language models on your phone. After download, Phone chat can work offline.",technical:"Official pinned LFM2 350M, LFM2 700M and LFM2.5 1.2B Q4_K_M downloads. Physical-phone inference remains unverified for this preview.",benefit:"Think offline.",icon:Brain,color:"indigo",status:"PREVIEW"},
{id:"lmstudio",title:"Your computer, connected",headline:"Bring your desktop models along.",description:"Use the Computer picker to chat with a reachable LM Studio server. Discover models and see connection progress or errors.",technical:"Same-Wi-Fi setup or authenticated remote HTTPS with a separately configured private network. Your computer must be awake. Direct LM Link pairing is not implemented.",benefit:"Use your own compute.",icon:Monitor,color:"cyan",status:"PREVIEW"},
{id:"providers",title:"Your choice of cloud",headline:"One space. More possibilities.",description:"Connect OpenAI, Gemini, Anthropic, Alibaba Cloud, NVIDIA or a compatible provider with your API key.",technical:"Computer and Cloud requests can include up to 20 recent messages, personal instructions and attached text, after a send disclosure. Provider charges and privacy terms apply.",benefit:"Choose a provider.",icon:Cloud,color:"blue",status:"PREVIEW"},
{id:"web-tools",title:"Answers with sources",headline:"Follow the thought to its source.",description:"Supported OpenAI and Anthropic models can use provider web search and return clickable citations.",technical:"Provider web tools are available unless disabled in provider settings. This sends chat context to the provider, which may search through its services. Not available for every model or endpoint.",benefit:"Explore source material.",icon:Globe,color:"cyan",status:"MODEL-DEPENDENT"},
{id:"five-themes",title:"Five shades of Moonlight",headline:"Find your light.",description:"Glass, Glass Night, Paper, Mono and Midnight, with system appearance and a saved Reduce Motion preference.",technical:"Appearance preferences persist locally. Screens shown on this site are browser captures of the app UI preview.",benefit:"Make it yours.",icon:Palette,color:"violet",status:"PREVIEW"},
{id:"credentials",title:"Saved connections",headline:"Keep your setup close.",description:"Reconnect using saved provider settings and encrypted API credentials.",technical:"Native AES-GCM credential storage uses Android Keystore. Chat history uses separate private MMKV storage. Private-network HTTP is opt-in and unencrypted without another protection layer.",benefit:"Less repeated setup.",icon:ShieldCheck,color:"emerald",status:"PREVIEW"},
{id:"responses",title:"Your response style",headline:"A little more you.",description:"Choose concise, balanced or detailed responses and save personal instructions.",technical:"Personal instructions are included in Computer and Cloud requests. Saved local memories are not automatically sent in those modes.",benefit:"Set the tone.",icon:SlidersHorizontal,color:"orange",status:"PREVIEW"},
{id:"voice",title:"Voice input",headline:"Catch the thought.",description:"Use Android speech recognition to turn spoken ideas into text for your conversation.",technical:"Android’s speech service may process audio online. Transcripts follow the selected Phone, Computer or Cloud mode.",benefit:"Speak your prompt.",icon:Mic,color:"pink",status:"PREVIEW"},
{id:"conversations",title:"A place for every thought",headline:"Pick up the thread.",description:"Search, rename and delete conversations. Review or remove locally saved memories and share selected text when you choose.",technical:"Conversations and memories persist in private app storage. Android cloud backup is disabled. Shared copies and online provider data must be managed separately.",benefit:"Stay organized.",icon:MessageSquare,color:"amber",status:"PREVIEW"},
{id:"files",title:"Text, with context",headline:"Bring your notes along.",description:"Attach supported text files to summarize notes, inspect code or work through a document.",technical:"The native reader accepts up to 512 KiB of UTF-8 text. Attached text stays local in Phone mode and can be transmitted in Computer or Cloud mode after confirmation.",benefit:"Work with your documents.",icon:FileCheck,color:"blue",status:"PREVIEW"},
{id:"model-checks",title:"Models that fit",headline:"A more careful use of memory.",description:"Capacity checks filter phone downloads and run again before loading. Model loads are serialized.",technical:"ARM64, at least 4 GiB total RAM, file size plus 1.5 GiB available RAM, a 1.3 GiB file cap, two threads and 1024 context. Compatibility checks do not guarantee device safety.",benefit:"Reduce memory pressure.",icon:Cpu,color:"emerald",status:"PREVIEW"},
{id:"updates",title:"Stay in the loop",headline:"A heads-up when there’s more.",description:"An in-app notice can point you to a newer Google Play version when one is available for your installation.",technical:"Foreground update checks through Google Play are limited to once per hour in the running app. Availability is not verified for the separate preview package.",benefit:"Find app updates.",icon:Download,color:"indigo",status:"PREVIEW"},
];
export const comingSoonFeatures:Feature[]=[];
